color0 #0b3b61
color1 #ff3a3a
color2 #52ffcf
color3 #fff383
color4 #1376f8
color5 #a277ff
color6 #ff5dd4
color7 #15fca2
color8 #62686c
color9 #ff54b0
color10 #73ffd8
color11 #fcf4ad
color12 #378dfe
color13 #ae81ff
color14 #ff69d7
color15 #5ffbbe

cursor                #38ff9c
cursor_text_color     #010b17
background            #010b17
foreground            #ebddf4
selection_foreground  #010b17
selection_background  #38ff9c
active_border_color   #a277ff
inactive_border_color #1a2b39
url_color             #a277ff

active_tab_foreground   #141414
active_tab_background   #a277ff
inactive_tab_foreground #708493
inactive_tab_background #1a2b39
cursor_trail_color      #708493
