-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)
hl.on("hyprland.start", function ()
  hl.exec_cmd("noctalia")
  hl.exec_cmd("fcitx5 -d --replace")
--  hl.exec_cmd("systemctl --user start polkit-gnome-authentication-agent-1")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
end)
