[main]
include=~/.config/foot/themes/noctalia

font=MesloLGS Nerd Font:size=14
pad=10x10 

#[colors-dark]
#foreground=ebddf4
#background=010b17
#
### Normal/regular colors (color palette 0-7)
#regular0=0b3b61  # black
#regular1=ff3a3a  # red
#regular2=52ffcf  # green
#regular3=fff383  # yellow
#regular4=1376f8  # blue
#regular5=c792ea  # magenta
#regular6=ff5dd4  # cyan
#regular7=15fca2  # white
#
### Bright colors (color palette 8-15)
#bright0=62686c   # bright black
#bright1=ff54b0   # bright red
#bright2=73ffd8   # bright green
#bright3=fcf4ad   # bright yellow
#bright4=378dfe   # bright blue
#bright5=ae81ff   # bright magenta
#bright6=ff69d7   # bright cyan
#bright7=5ffbbe   # bright white
#
### dimmed colors (see foot.ini(5) man page)
#dim0=ff9e64
#dim1=db4b4b
#
#cursor=000000 38ff9c
#
#alpha=0.9
